name: Griefalerts
version: ${project.version}
main: by.skalem.griefalerts.griefalerts.Griefalerts
api-version: 1.16
authors: [ Skalem ]
description: Helps admins to cope with griefers

permissions:
  Griefalerts.*:
    description: allows to us /gf command
    default: op

commands:
  gf:
    description: overall command for commands of griefalerts plugin
    usage: /gf <stop,friend> <time,player1> <nothing,player2>
    permission: Griefalerts.command